### ISSUE TITLE
Uncaught TypeError: Cannot read property 'querySelector' of undefined

### ISSUE THREAD

**Issue by DomVinyard** [olmokramer/atom-stylus-autocompile#14]
[Enter steps to reproduce below:]
Straight out of the box.

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [stylus-autocompile](https://github.com/olmokramer/atom-stylus-autocompile) package, v0.6.1
### Stack Trace

Uncaught TypeError: Cannot read property 'querySelector' of undefined

```
At /Users/x/.atom/packages/stylus-autocompile/lib/stylus-autocompile-view.js:71

TypeError: Cannot read property 'querySelector' of undefined
    at getFiles (/Users/x/.atom/packages/stylus-autocompile/lib/stylus-autocompile-view.js:71:14)
    at showView (/Users/x/.atom/packages/stylus-autocompile/lib/stylus-autocompile-view.js:44:10)
    at /Users/x/.atom/packages/stylus-autocompile/lib/stylus-autocompile.js:131:7
    at /Users/x/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/regenerator/node_modules/commoner/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:82:15)
```
### Commands

```
     -0:47.8.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
  2x -0:47.2.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:45.1.0 core:copy (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:43.9.0 core:cut (atom-text-editor.editor.is-focused)
     -0:43.2.0 core:paste (atom-text-editor.editor.is-focused)
     -0:41.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:41 editor:newline (atom-text-editor.editor.is-focused)
     -0:38.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:21.2.0 core:copy (atom-text-editor.editor.is-focused)
     -0:20.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:15.2.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:02.9.0 core:copy (atom-text-editor.editor.is-focused)
     -0:02.7.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:02.7.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:02.7.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:00.7.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "terminal-panel",
      "atom-terminal-panel",
      "terminal-plus",
      "status-bar",
      "git-time-machine",
      "git-diff"
    ],
    "projectHome": "/Users/x/Dev",
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "stylus-autocompile": {}
}
```
### Installed Packages

``` coffee
# User
Stylus, v3.0.0
atom-jade, v0.3.0
coffee-compile, v0.21.1
file-icons, v1.7.15
highlight-selected, v0.11.2
jade-autocompile, v0.8.3
one-tab, v0.9.0
pane-by-type, v1.0.1
simple-drag-drop-text, v0.3.1
stylus-autocompile, v0.6.1
term3, v0.22.1
tidy-tabs, v0.3.0

# Dev
No dev packages
```

**Comment by DomVinyard** [comment]
I should add, the module works perfectly, no issues whatsoever except for the infuriating error dialogue box.
