### ISSUE TITLE
Failed to activate the stylus-autocompile package

### ISSUE THREAD

**Issue by noproblama** [olmokramer/atom-stylus-autocompile#18]
Just started printing new stuff to my existing styl file. 

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Linux Mint
**Thrown From**: [stylus-autocompile](https://github.com/olmokramer/atom-stylus-autocompile) package 0.6.1

### Stack Trace

Failed to activate the stylus-autocompile package

```
At Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at Error (native)
    at StatusBarView.module.exports.StatusBarView.addLeftTile (/app.asar/node_modules/status-bar/lib/status-bar-view.js:67:22)
    at initView (/packages/stylus-autocompile/lib/stylus-autocompile-view.js:26:20)
    at Object.consumeStatusBar (/packages/stylus-autocompile/lib/stylus-autocompile.js:36:3)
    at Provider.module.exports.Provider.provide (/app.asar/node_modules/service-hub/lib/provider.js:29:52)
    at ServiceHub.module.exports.ServiceHub.consume (/app.asar/node_modules/service-hub/lib/service-hub.js:50:18)
    at Package.module.exports.Package.activateServices (/app.asar/src/package.js:404:75)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:221:16)
    at /app.asar/src/package.js:876:25
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:240:20)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
  2x -0:42.4.0 core:select-left (input.hidden-input)
     -0:28.9.0 core:backspace (input.hidden-input)
  6x -0:27.6.0 editor:move-to-end-of-word (input.hidden-input)
     -0:25.7.0 editor:delete-to-beginning-of-word (input.hidden-input)
     -0:25.1.0 core:paste (input.hidden-input)
     -0:22.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
autocompiler-pug-jade 2.0.1 
build 0.67.0 
build-stylus 0.8.1 
busy 0.7.0 
gtk-dark-theme 0.1.4 
language-pug 0.0.21 
platformio-ide-terminal 2.5.0 
semanticolor 3.4.10 
shadow 0.1.0 
Stylus 3.1.0 
stylus-autocompile 0.6.1 
```

**Comment by frog42** [comment]
Same...
